      SUBROUTINE DT_BDINIT

      CALL DT_BLKD43
      CALL DT_BLKD46
      CALL DT_BLKD47
      CALL DT_DEFSET
      CALL DT_HADPRP
      CALL DT_NONAME
      CALL DT_RUNTT
      CALL DT_ZK
      CALL PYDATA
      END